version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-domino
    ports:
      - "8080:80"
    volumes:
      - .:/code
      - ./docker/nginx/local/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    networks:
      - code-network
    volumes:
      - .:/code
    environment:
      - APP_STORAGE=files

networks:
  code-network:
    driver: bridge
